### ISSUE TITLE
Error running SVC

### ISSUE THREAD

**Issue by bittlingmayer** [ghpaetzold/questplusplus#27]
I get `ValueError: continuous is not supported` when I run with svc.cfg.

```
$ python src/learn_model.py config/svc.cfg 
INFO:root:Opening input files ...
INFO:root:Scaling datasets...
kernel ['linear', 'rbf']
INFO:root:Tuning hyper-parameters for f1_score
/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/grid_search.py:347: DeprecationWarning: Passing a loss function is deprecated and will be removed in 0.15. Either use strings or score objects. The relevant new parameter is called ''scoring''. 
  score_func=self.score_func)
Fitting 5 folds for each of 8 candidates, totalling 40 fits
Traceback (most recent call last):
  File "src/learn_model.py", line 505, in <module>
    sys.exit(main())
  File "src/learn_model.py", line 494, in main
    run(config)
  File "src/learn_model.py", line 437, in run
    y_hat = fit_predict(config, X_train, y_train, X_test, y_test, config.get("ref_thd", None))
  File "src/learn_model.py", line 330, in fit_predict
    estimator, scorers = set_learning_method(config, X_train, y_train)
  File "src/learn_model.py", line 232, in set_learning_method
    o.get('n_jobs', 1))
  File "src/learn_model.py", line 175, in optimize_model
    clf.fit(X_train, y_train)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/grid_search.py", line 596, in fit
    return self._fit(X, y, ParameterGrid(self.param_grid))
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/grid_search.py", line 378, in _fit
    for parameters in parameter_iterable
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 653, in __call__
    self.dispatch(function, args, kwargs)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 138, in __init__
    self.results = func(*args, **kwargs)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1240, in _fit_and_score
    test_score = _score(estimator, X_test, y_test, scorer)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1296, in _score
    score = scorer(estimator, X_test, y_test)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/metrics/scorer.py", line 80, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/metrics/metrics.py", line 1398, in f1_score
    sample_weight=sample_weight)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/metrics/metrics.py", line 1495, in fbeta_score
    sample_weight=sample_weight)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/metrics/metrics.py", line 1669, in precision_recall_fscore_support
    y_type, y_true, y_pred = _check_clf_targets(y_true, y_pred)
  File "/Users/bittlingmayer/anaconda/lib/python2.7/site-packages/sklearn/metrics/metrics.py", line 127, in _check_clf_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: continuous is not supported
```

I'm running scikit-learn 0.15.2 (on Anaconda).

**Comment by kaayushi** [comment]
Any help on this one?
I am also having the same problem

**Comment by carolscarton** [comment]
The example being used by config/svc.cfg is wrong. The .effort files contains continuous values and should only be used for regression and not for classification. If you try discrete labels, this functionality works fine. I will update this examples asap.
